version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /myapp-api/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/myapp-api
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: ${RAILS_ENV:-development}
      DEVISE_JWT_SECRET_KEY: ${DEVISE_JWT_SECRET_KEY}
      GMAIL_SMTP_USER: ${GMAIL_SMTP_USER}
      GMAIL_SMTP_PASSWORD: ${GMAIL_SMTP_PASSWORD}
      APP_NAME: ${APP_NAME}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - db
      - redis

  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    command: sh -c "cd myapp-front && npm install && npm start"
    ports:
      - "3001:3000"
    volumes:
      - ./front:/usr/src/app

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  sidekiq:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - ./api:/myapp-api
    environment:
      REDIS_URL: ${REDIS_URL}
      GMAIL_SMTP_USER: ${GMAIL_SMTP_USER}
      GMAIL_SMTP_PASSWORD: ${GMAIL_SMTP_PASSWORD}
    depends_on:
      - db
      - redis
